PaymezonApp/PaymezonApp/Models/RechargeViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using PaymezonDAL;

namespace PaymezonApp.Models
{
    public class RechargeViewModels
    {
        public int Pk_Recharge_Id { get; set; }
        public string Operator_Code { get; set; }
        public decimal Mobile_no { get; set; }
        public decimal Amount { get; set; }
        public string Transaction_Id { get; set; }
        public string Type { get; set; }
        public string Agent_Id { get; set; }
        public Nullable<long> Fk_RegisterId { get; set; }
        public string Circle_Code { get; set; }
        public string Action_On_Amount { get; set; }
        public Nullable<System.DateTime> Recharge_Date { get; set; }
        public Nullable<System.DateTime> Response_Date { get; set; }
        public string Transaction_Log { get; set; }
        public string Status { get; set; }
        public string Ref_number { get; set; }
        public string User_Type { get; set; }
        public Nullable<long> Recharge_By { get; set; }
        public List<Company_Detail> List_Company { get; set; }
        public List<Recharge_Detail> RCG_List { get; set; }
        public List<Recharge_Detail> countrech_List { get; set; }
        public List<Transaction_Table> list_transaction { get; set; }
        public TransactionStatus transaction { get; set; }
        [Required(ErrorMessage = "Please Select From Date")]
        public string fromdate { get; set; }
        [Required(ErrorMessage = "Please Select To Date")]
        public string todate { get; set; }
        public string message { get; set; }
    }
}

PaymezonApp/PaymezonApp/Controllers/RechargeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PaymezonBAL;
using PaymezonApp.Models;
using PaymezonDAL;

namespace PaymezonApp.Controllers
{
    public class RechargeController : Controller
    {
        //
        // GET: /Recharge/
        public ActionResult Index()
        {
            if (Session["U_ID"] != null)
            {
                string fromdate = System.DateTime.Now.ToString();
                string todate = "";
                long ID = Convert.ToInt64(Session["U_ID"]);
                PaymezonDBEntities1 db = new PaymezonDBEntities1();
                RechargeViewModels Rcglist = new RechargeViewModels();
                Rcglist.RCG_List = RechargeBAL.RCG_List_byId(ID,fromdate,todate);
                return View(Rcglist);
            }
            else
            {
                return RedirectToAction("../Register/Login");
            }
        }
        [HttpPost]
        public ActionResult Index(RechargeViewModels  reg)
        {
            if (Session["U_ID"] != null)
            {
                long ID = Convert.ToInt64(Session["U_ID"]);
                PaymezonDBEntities1 db = new PaymezonDBEntities1();
                RechargeViewModels Rcglist = new RechargeViewModels();
                if (ModelState.IsValid)
                {
                   
                    Rcglist.RCG_List = RechargeBAL.RCG_List_byId(ID, reg.fromdate, reg.todate);
                    return View(Rcglist);
                }
                else
                {
                    reg.fromdate = System.DateTime.Now.ToString();
                    reg.todate = "";
                    Rcglist.RCG_List = RechargeBAL.RCG_List_byId(ID, reg.fromdate, reg.todate);
                    Rcglist.message = "Please Select Valid From Date And From Date";
                    return View(Rcglist);
                }
            }
            else
            {
                return RedirectToAction("../Register/Login");
            }
        }

   

        public PartialViewResult AddNewRecharge()
        {
            PaymezonDBEntities1 db = new PaymezonDBEntities1();
            RechargeViewModels obj = new RechargeViewModels();
            obj.List_Company = CompanyBAL.CompanyList();
            return PartialView(obj);
        }
        public ActionResult AddRecharge(Models.RechargeViewModels reg)
        {
            try
            {
                CommonApi api = new CommonApi();
                string txnId = "TN" + DateTime.Now.Year + DateTime.Now.Ticks.ToString("D" + 3);
                string refNo = "RF" + DateTime.Now.Ticks.ToString("D" + 5);
                string apiName = "";
                PaymezonDBEntities1 db = new PaymezonDBEntities1();
                Recharge_Detail usr = new Recharge_Detail();

                long ID = Convert.ToInt64(Session["U_ID"]);
                string labelID = Convert.ToString(this.Session["Label_ID"]);
                string usertype = Convert.ToString(this.Session["User_Type"]);
                UserRegistration usrs = RegistrationDAL.CheckUserbyId(ID);
                string strmsg = Utility.CheckRechargeDetail(reg.Amount, usrs, Convert.ToInt64(reg.Mobile_no) );
                if (strmsg == "Succ")
                {

                    usr.Action_On_Amount = "Dr";
                    usr.Circle_Code = "8";
                    usr.Operator_Code = reg.Operator_Code;
                    usr.Mobile_no = reg.Mobile_no;
                    usr.Amount = reg.Amount;
                    usr.Transaction_Id = "TN" + DateTime.Now.Year + DateTime.Now.Ticks.ToString("D" + 3);  //new Random().Next();
                    usr.Ref_number = "RF" + DateTime.Now.Ticks.ToString("D" + 5);  // new Random().Next();
                    usr.Agent_Id = labelID;
                    usr.User_Type = usertype;
                    usr.Recharge_Date = System.DateTime.Now;
                    usr.Recharge_By = ID;
                    usr.Fk_RegisterId = ID;
                    usr.Status = "Pending";
                    usr.ipAdd = Utility.GetMacAddress();
                    //db.Recharge_Detail.Add(usr);

                    //db.SaveChanges();
                    string strMsgAmt = PaymezonBAL.RechargeBAL.InsertRegBAL(usr);
                    Session["Amt"] = strMsgAmt;
                    Utility.balance = Convert.ToDecimal(strMsgAmt);
                   
                }
                return RedirectToAction("../Recharge/Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

    }
}

PaymezonApp/PaymezonApp/Views/Recharge/AddNewRecharge.cshtml
@model PaymezonApp.Models.RechargeViewModels

<link rel="stylesheet" type="text/css" id="theme" href="@Url.Content("~/css/theme-default.css")" />

<div class="modal fade" id="iconPreview" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            @using (Html.BeginForm("AddRecharge", "Recharge", FormMethod.Post))
            {
               
                
                
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Add New Recharge</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">

                        <div class="row">
                            <div class="col-md-12">
                                <div class="panel-body">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="col-md-4 col-xs-12 control-label">Operator</label>
                                            <div class="col-md-8 col-xs-12">
                                                <div class="input-group">

                                                    @Html.DropDownListFor(model => model.Operator_Code, new SelectList(Model.List_Company, "Company_Name", "Company_Name"), new { @class = "form-control select" })
                                                </div>
                                                <span class="help-block">Please Select Your Operator</span>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-4 col-xs-12 control-label">Mobile Number</label>
                                            <div class="col-md-8 col-xs-12">
                                                <div class="input-group">

                                                    @Html.TextBoxFor(model => model.Mobile_no, new { @class = "form-control ", @type = "number", maxlength = "10"})
                                                
                                                </div>
                                                <span class="help-block">Please Enter Mobile Number</span>
                                            </div>
                                        </div>
                                      
                                        <div class="form-group">
                                            <label class="col-md-4 col-xs-12 control-label">Amount</label>
                                            <div class="col-md-8 col-xs-12">
                                                <div class="input-group">

                                                    @Html.TextBoxFor(model => model.Amount, new { @class = "form-control ", @type = "number", @maxlength = "10" })
                                                   
                                                </div>
                                                <span class="help-block">Please Enter Amount</span>
                                            </div>
                                        </div>

                                    </div>
                                   
                                </div>
                             
                            </div>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-md-10">
                        <button class="btn btn-info mb-control" id="btnsave">Recharge</button>
                    </div>
                    <button type="button" class="btn btn-primary" data-dismiss="modal" data-target="#OpenDilog">Close</button>
                </div>
            }
        </div>
    </div>
</div>


<script>

    $(function () {

        $(".dt").datepicker();

        if ($(this).find("i").length > 0) {
            var iClass = $(this).find("i").attr("class");
        } else {
            var iClass = $(this).find("span").not("span[class=glyphicon-class]").attr("class");
        }

        var icon_preview = $("<i></i>").addClass(iClass);

        $("#iconPreview .icon-preview").html(icon_preview);

        $("#iconPreview .icon-preview-span").html('&lt;span class="' + iClass + '">&lt;/span>');
        $("#iconPreview .icon-preview-i").html('&lt;i class="' + iClass + '">&lt;/i>');
        $("#iconPreview .icon-preview-class").html(iClass);

        $("#iconPreview").modal("show");

    });
</script>

<style type="text/css">
    div.datepicker {
        z-index: 10000 !important;
    }
</style>


PaymezonApp/PaymezonApp/Views/Recharge/Index.cshtml
@model PaymezonApp.Models.RechargeViewModels
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
  
      <div class="row clearfix">
        
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
       
            <br/>
            <br/>
@using (Html.BeginForm("Index", "Recharge", FormMethod.Post))
      {
            <div class="panel panel-success panel-hidden-controls">
                <div class="panel-heading">
                    <h3 class="panel-title">Recharge Details</h3>
                </div>
                <div class="panel-body">

                    <div class="col-md-4">
                        <label class="col-md-4 control-label">From Date :</label>
                        <div class="input-group">
                            <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
                          
                            @Html.TextBoxFor(model => model.fromdate, new { @class = "form-control dt", @placeholder = "Please choose a date..." })
                          
                        </div>
                        <br />
                        <p style="color: red;">@Html.DisplayFor(model => model.message)</p>
                    </div>
                    <div class="col-md-4">
                        <label class="col-md-4 control-label">To Date :</label>
                        <div class="input-group">
                            <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
                            @Html.TextBoxFor(model => model.todate, new { @class = "form-control dt", @placeholder = "Please choose a date..." })
                           
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                
                    <input type="button" id="show" name="name" class="btn btn-success pull-left" value="Add New Recharge" onclick="AddRecharge();" />

                    <button class="btn btn-success pull-right">Search</button>
                </div>
            </div>
       }
            <div class="panel panel-default">
                <div class="panel-body">

                    <table class="table datatable" id="Recharge" cellspacing="0" cellpadding="3" rules="all" border="1" style="background-color: White; border-color: #CCCCCC; border-width: 1px; border-style: None; font-weight: normal; font-style: normal; text-decoration: none; width: 100%; border-collapse: collapse; ">

                        <thead>
                            <tr align="left" style="color:Black;background-color:#DBE4E8;font-weight:bold;">
                                <th scope="col">Sr No.</th>
                                <th scope="col">Recharge Date</th>
                                <th scope="col">API Transaction Id</th>
                                <th scope="col">Client Transaction Id</th>
                                <th scope="col">Operator Code</th>
                                <th scope="col">Mobile No</th>
                                <th scope="col">Amount</th>
                                <th scope="col">Status</th>
                                <th>Complain Here</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{int i = 0;}
                            @foreach (var item in Model.RCG_List)
                            {
                                i++;

                                <tr align="left" valign="middle" style="color:#000066;background-color:White;">
                                    <td>@i</td>
                                    <td>@item.Recharge_Date.Date.ToShortDateString()</td>
                                    <td>@item.Transaction_Id</td>
                                    <td>@item.C_Tranx_ID</td>
                                    <td>@item.Operator_Code</td>
                                    <td>@item.Mobile_no</td>
                                    <td>@item.Amount</td>
                                    <td>@item.Status</td>
                                   <td><a href="javascript:void(0);" onclick="AddSupport('@item.Amount','@item.Mobile_no','@item.Operator_Code');">Support</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div id='OpenDilog'></div>
            </div>
        
        </div>
    </div>
</div>
<script type="text/javascript">
    //$(document).ready(function () {
    //    setInterval(function () {             
    //        $.ajax({
    //            url: "/Recharge/Index",
    //            type: "POST",
    //        });
    //    },5000);
    //});
    $(document).ready(function () {
        window.setInterval(function () {
            var url = $("#Recharge");
            $('#Recharge').load(url)
        }, 9000);
        $.ajaxSetup({ cache: false });
    });

    

    function AddSupport() {
        debugger;
        var div = $("#OpenDilog");
       
        //$.mpb('show', { value: [0, 30], speed: 10, state: 'success' });
        div.load("/Recharge/AddNewRecharge", function () {
            //$.mpb("update", {
            //    value: 100, speed: 5, complete: function () {
            //        $(".mpb").fadeOut(200, function () {
            //            $(this).remove();
            //        });
            //    }
            //});
            div.modal('show', { backdrop: 'static' });
        });
    }
   
  
</script>



