PaymezonApp/PaymezonApp/Controllers/ALLReportController.cs
using Newtonsoft.Json;
using PaymezonApp.Models;
using PaymezonBAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace PaymezonApp.Controllers
{
    public class ALLReportController : Controller
    {
        public ActionResult FundReport()
        {
            try
            {
                if (Session["U_ID"] != null)
                {
                    string  fromdate = System.DateTime.Today.ToString();
                    string todate = "";
                    long ID = Convert.ToInt64(Session["U_ID"]);
                    UserWalletViewModel WalletLIST = new UserWalletViewModel();
                    WalletLIST.List_UserWallet_BYId = ALLReportBAL.ListWallet_By_Id(ID,fromdate,todate);
                    return View(WalletLIST);
                }
                else
                {
                    return RedirectToAction("../Register/Login");
                }
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult FundReport(UserWalletViewModel reg)
        {
            try
            {
                if (Session["U_ID"] != null)
                {
                    long ID = Convert.ToInt64(Session["U_ID"]);
                    UserWalletViewModel WalletLIST = new UserWalletViewModel();
                    if (ModelState.IsValid)
                    {
                        WalletLIST.List_UserWallet_BYId = ALLReportBAL.ListWallet_By_Id(ID, reg.fromdate, reg.todate);
                        return View(WalletLIST);
                    }
                    else
                    {
                        WalletLIST.message = "Please Enter Valid From Date Or To Date ";
                        reg.fromdate = System.DateTime.Now.Date.ToString();
                        reg.todate = "";
                        WalletLIST.List_UserWallet_BYId = ALLReportBAL.ListWallet_By_Id(ID, reg.fromdate, reg.todate);
                        return View(WalletLIST);
                    }
                }
                else
                {
                    return RedirectToAction("../Register/Login");
                }
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        public ActionResult OperatorWiseReport()
        {
            if (Session["U_ID"] != null)
            {
                long ID = Convert.ToInt64(Session["U_ID"]);

                TransactionModel opwiselist = new TransactionModel();
                opwiselist.transanctionlist = ALLReportBAL.opwise_by_id(ID);
                return View(opwiselist);
            }
            else
            {
                return RedirectToAction("../Register/Login");
            }


            return View();
        }
        public ActionResult DailyReport()
        {

            if (Session["U_ID"] != null)
            {
                long ID = Convert.ToInt64(Session["U_ID"]);
                string todaydate = "";
                TransactionStatus opwiselist = new TransactionStatus();
                // opwiselist.transtts = Utility.CountTransaction(ID, todaydate);
                opwiselist.listtransaction = Utility.CountTransactionforuser(ID, todaydate);
                return View(opwiselist);
            }
            else
            {
                return RedirectToAction("../Register/Login");
            }
        }
        [HttpPost]
        public ActionResult DailyReport(TransactionStatus reg)
        {
            long ID = Convert.ToInt64(Session["U_ID"]);
            TransactionStatus opwiselist = new TransactionStatus();
            if (Session["U_ID"] != null)
            {
                if (ModelState.IsValid)
                {
                    opwiselist.listtransaction = Utility.CountTransactionforuser(ID, reg.dailydate);
                    return View(opwiselist);
                }
                else
                {
                    reg.dailydate = "";
                    opwiselist.listtransaction = Utility.CountTransactionforuser(ID, reg.dailydate);
                    opwiselist.message = "Please Enter Date .!";
                    return View(opwiselist);
                }
            }
            else
            {
                return RedirectToAction("../Register/Login");
            }
        }

        public ActionResult AccountReport()
        {
            if (Session["U_ID"] != null)
            {
                long ID = Convert.ToInt64(Session["U_ID"]);

                TransactionModel opwiselist = new TransactionModel();
                opwiselist.transanctionlist = ALLReportBAL.account_report_byID(ID);
                return View(opwiselist);
            }
            else
            {
                return RedirectToAction("../Register/Login");
            }


            //return View();
        }

        public ActionResult Jioreport() 
        {
            try
            {
                List<Vendor_InptOutPut_ReqDetailsViewModels> listvendormodel = new List<Vendor_InptOutPut_ReqDetailsViewModels>();
              //  DateTime? fdate, DateTime? tdate
                string fdate = System.DateTime.Today.Date.ToString();
                string tdate = ""; 
              
                    long ID = Convert.ToInt64(Session["U_ID"]);
                    TransactionModel jioselist = new TransactionModel();
                    jioselist.listvendr = ALLReportBAL.jioresponsereport(fdate, tdate);
                    foreach (var item in jioselist.listvendr)
                    {
                        Vendor_InptOutPut_ReqDetailsViewModels model = new Vendor_InptOutPut_ReqDetailsViewModels();
                        model.S_No = item.S_No;
                        model.REFERENCE_NUMBER = item.REFERENCE_NUMBER;
                        model.ReqDate = item.ReqDate;
                        model.ResDate = item.ResDate;
                        model.Output_Responce = item.Output_Responce;
                        string[] msg = model.Output_Responce.Split(',');
                        model.Output_Responce = msg[7].ToString();
                        model.Service_name = item.Service_name;
                        listvendormodel.Add(model);
                    }
                    jioselist.listvendrreqmdl = listvendormodel;
                    return View(jioselist);
             
                
            }
            catch (Exception)
            {

                return View();
            }
            
        }
        [HttpPost]
        public ActionResult Jioreport(TransactionModel reg)
        {
            long ID = Convert.ToInt64(Session["U_ID"]);
            TransactionModel jioselist = new TransactionModel();
            try
            {
                List<Vendor_InptOutPut_ReqDetailsViewModels> listvendormodel = new List<Vendor_InptOutPut_ReqDetailsViewModels>();
                //  DateTime? fdate, DateTime? tdate
           
                              
                if (ModelState.IsValid)
                {
                    jioselist.listvendr = ALLReportBAL.jioresponsereport(reg.fromdate, reg.todate);
                    foreach (var item in jioselist.listvendr)
                    {
                        Vendor_InptOutPut_ReqDetailsViewModels model = new Vendor_InptOutPut_ReqDetailsViewModels();
                        model.S_No = item.S_No;
                        model.REFERENCE_NUMBER = item.REFERENCE_NUMBER;
                        model.ReqDate = item.ReqDate;
                        model.ResDate = item.ResDate;
                        model.Output_Responce = item.Output_Responce;
                        try
                        {
                            string[] msg = model.Output_Responce.Split(',');
                            model.Output_Responce = msg[7].ToString();
                        }
                        catch (Exception ex)
                        {
                            model.Output_Responce = item.Output_Responce;
                        }                       
                        model.Service_name = item.Service_name;
                        listvendormodel.Add(model);
                    }
                    jioselist.listvendrreqmdl = listvendormodel;
                    return View(jioselist);
                }
                else
                {
                   string fdate = System.DateTime.Today.Date.ToString();
                    string tdate = "";
                    jioselist.listvendr = ALLReportBAL.jioresponsereport(fdate, tdate);
                    foreach (var item in jioselist.listvendr)
                    {
                        Vendor_InptOutPut_ReqDetailsViewModels model = new Vendor_InptOutPut_ReqDetailsViewModels();
                        model.S_No = item.S_No;
                        model.REFERENCE_NUMBER = item.REFERENCE_NUMBER;
                        model.ReqDate = item.ReqDate;
                        model.ResDate = item.ResDate;
                        model.Output_Responce = item.Output_Responce;
                        string[] msg = model.Output_Responce.Split(',');
                        model.Output_Responce = msg[7].ToString();
                        model.Service_name = item.Service_name;
                        listvendormodel.Add(model);
                    }
                    jioselist.listvendrreqmdl = listvendormodel;
                    jioselist.message = "Please Select or Enter Valid FromDate And Todate..!";
                    return View(jioselist);
                }
              


            }
            catch (Exception)

PaymezonApp/PaymezonApp/Views/AllReport/AccountReport.cshtml
@model PaymezonApp.Models.TransactionModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <br />
                <div class="header">
                    <h2>
                        Account Report
                    </h2>
                </div>

                <br>
                <br>

            </div>

            <div class="panel panel-default">
                <div class="panel-body">

                    <table class="table datatable" id="UserWallet" cellspacing="0" cellpadding="3" rules="all" border="1" style="background-color: White; border-color: #CCCCCC; border-width: 1px; border-style: None; font-weight: normal; font-style: normal; text-decoration: none; width: 100%; border-collapse: collapse; ">

                        <thead>
                            <tr align="left" style="color:Black;background-color:#DBE4E8;font-weight:bold;">
                                <th scope="col">Sr No.</th>
                                <th scope="col">Date </th>
                                <th scope="col">Recharge Id</th>
                                <th scope="col">Company Name</th>
                                <th scope="col">Number</th>
                                <th scope="col">Amount</th>
                                <th scope="col">Status</th>
                                <th scope="col">Net Amount</th>
                                <th scope="col">Commision</th>
                                <th scope="col">Balance</th>
                                <th scope="col">Support</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{int i = 0;}
                            @foreach (var item in Model.TransactionModel)
                            {
                                i++;

                                <tr align="left" valign="middle" style="color:#000066;background-color:White;">
                                    <td>@i</td>
                                    <td>@item.Created_Date</td>
                                    <td>@item.Ref_No</td>
                                    <td>@item.Service_Name</td>
                                    <td>@item.MobileNo</td>
                                    <td>@item.Request_Amount</td>
                                    <td>@item.Status</td>
                                    <td>@item.Net_Amount</td>
                                    <td>@item.Total_Commision</td>
                                    <td>@item.Final_Bal_Amount</td>
                                    <td></td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div id='OpenDilog'></div>
            </div>

        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {

    });
</script>


PaymezonApp/PaymezonApp/Views/AllReport/DailyReport.cshtml
@model PaymezonApp.Models.TransactionStatus
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            @*<div class="card">
                <br />
                <div class="header">
                    <h2>
                        Daily Report
                    </h2>
                </div>

                <br>
                <br>

            </div>*@
            <br />
            <br />
@using (Html.BeginForm("DailyReport", "ALLReport", FormMethod.Post))
      {
            <div class="panel panel-success panel-hidden-controls">
                <div class="panel-heading">
                    <h3 class="panel-title">Daily Report</h3>
                </div>

                <div class="panel-body">

                    <div class="col-md-4">
                        <label class="col-md-4 control-label">Select Date :</label>
                        <div class="input-group">
                            <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
                            @Html.TextBoxFor(model => model.dailydate, new { @class = "form-control dt", @placeholder = "Please choose a date..." })
                        </div>
                        <br/>
                        <p style="color: red;">@Html.DisplayFor(model => model.message)</p>
                    </div>
                    @*<div class="col-md-4">
                        <label class="col-md-4 control-label">To Date :</label>
                        <div class="input-group">
                            <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
                            <input type="text" class="form-control datepicker" />
                        </div>
                    </div>*@
                </div>
                <div class="panel-footer">
                    
                    <button class="btn btn-success pull-right">Search</button>
                </div>
            </div>
    
}
            <div class="panel panel-default">
                <div class="panel-body">

                    <table class="table datatable" id="UserWallet" cellspacing="0" cellpadding="3" rules="all" border="1" style="background-color: White; border-color: #CCCCCC; border-width: 1px; border-style: None; font-weight: normal; font-style: normal; text-decoration: none; width: 100%; border-collapse: collapse; ">

                        <thead>
                            <tr align="left" style="color:Black;background-color:#DBE4E8;font-weight:bold;">
                              
                                <th scope="col">Opening Balance</th>
                                <th scope="col">Total Recharge</th>
                                <th scope="col">Total Success</th>
                                <th scope="col">Total Failure</th>
                                
                                <th scope="col">Total Debit</th>
                                <th scope="col">Total Credit</th>
                                <th scope="col">Total Commmision In</th>
                                <th scope="col">Closing Balance</th>
                            </tr>
                        </thead>

                        <tbody>
                            @{int i = 1;}
                           @foreach (var item in Model.listtransaction)
                           {
                              
                            <tr align="left" valign="middle" style="color:#000066;background-color:White;">
                                   

                                    <td>@item.openingbalance</td>
                                    <td>@item.TotalTxn</td>
                                    <td>@item.SuccessAmount</td>
                                    <td>@item.FailureAmount</td>
                                    <td>@item.debitamount</td>
                                    <td>@item.creditamount</td>
                                    <td>@item.totalcommision</td>
                                    <td>@item.closingbalance</td>
                                </tr>

                                @*<tr align="left" valign="middle" style="color:#000066;background-color:White;">
                                    <td>@i</td>
                                   
                                    <td>@Model.transtts.TotalTxn</td>
                                    <td>@Model.transtts.SuccessAmount</td>
                                    <td>@Model.transtts.FailureAmount</td>
                                    <td>@Model.transtts.fundamount</td>
                                    <td>@Model.transtts.debitamount</td>
                                    <td>@Model.transtts.creditamount</td>
                                    <td>@Model.transtts.totalcommision</td>
                                    <td>@Model.transtts.balance</td>
                                </tr>*@
                           }
                        </tbody>
                    </table>
                </div>
                <div id='OpenDilog'></div>
            </div>

        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {

    });
</script>


PaymezonApp/PaymezonApp/Views/AllReport/FundReport.cshtml
@model PaymezonApp.Models.UserWalletViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
           
            <br />
            <br />
@using (Html.BeginForm("FundReport", "ALLReport", FormMethod.Post))
      {
            <div class="panel panel-success panel-hidden-controls">
                <div class="panel-heading">
                    <h3 class="panel-title"> Re-Fund Report</h3>
                </div>
                <div class="panel-body">

                    <div class="col-md-4">
                        <label class="col-md-4 control-label">From Date :</label>
                        <div class="input-group">
                            <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
                            @Html.TextBoxFor(model => model.fromdate, new { @class = "form-control dt", @placeholder = "Please choose a date..." })
                        </div>
                        <br/>
                        <p style="color: red;">@Html.DisplayFor(model => model.message)</p>
                    </div>
                    <div class="col-md-4">
                        <label class="col-md-4 control-label">To Date :</label>
                        <div class="input-group">
                            <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
                            @Html.TextBoxFor(model => model.todate, new { @class = "form-control dt", @placeholder = "Please choose a date..." })
                        </div>
                    </div>
                </div>
                <div class="panel-footer">

                    <button class="btn btn-success pull-right">Search</button>
                </div>
            </div>
       }
            <div class="panel panel-default">
                <div class="panel-body">

                    <table class="table datatable" id="UserWallet" cellspacing="0" cellpadding="3" rules="all" border="1" style="background-color: White; border-color: #CCCCCC; border-width: 1px; border-style: None; font-weight: normal; font-style: normal; text-decoration: none; width: 100%; border-collapse: collapse; ">

                        <thead>
                            <tr align="left" style="color:Black;background-color:#DBE4E8;font-weight:bold;">
                                <th scope="col">Sr No.</th>
                                <th scope="col"> Date </th>
                                <th scope="col">User Name</th>
                                <th scope="col">Label ID</th>
                                <th scope="col">Fund Amount</th>
                                <th scope="col">Debit Amount</th>
                                <th scope="col">Credit Amount</th>
                                <th scope="col">Description</th>

                            </tr>
                        </thead>
                        <tbody>
                            @{int i = 0;}
                            @foreach (var item in Model.List_UserWallet_BYId)
                            {
                                i++;

                                <tr align="left" valign="middle" style="color:#000066;background-color:White;">
                                    <td>@i</td>
                                    <td>@item.Created_Date</td>
                                    <td>@item.User_Name</td>
                                    <td>@item.Label_Id</td>
                                    <td>@item.Fund_Amount</td>
                                    <td>@item.Debit_Amount</td>
                                    <td>@item.Credit_Amount</td>
                                    <td>@item.Description</td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div id='OpenDilog'></div>
            </div>

        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {

    });
</script>

PaymezonApp/PaymezonApp/Views/AllReport/OperatorWiseReport.cshtml
@Model PaymezonApp.Models.TransactionModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <br />
                <div class="header">
                    <h2>
                       OperatorWise Report
                    </h2>
                </div>

                <br>
                <br>

            </div>

            <div class="panel panel-default">
                <div class="panel-body">

                    <table class="table datatable" id="UserWallet" cellspacing="0" cellpadding="3" rules="all" border="1" style="background-color: White; border-color: #CCCCCC; border-width: 1px; border-style: None; font-weight: normal; font-style: normal; text-decoration: none; width: 100%; border-collapse: collapse; ">

                        <thead>
                            <tr align="left" style="color:Black;background-color:#DBE4E8;font-weight:bold;">
                                <th scope="col">Sr No.</th>
                                @*<th scope="col">Date </th>*@
                                <th scope="col">Operator Name</th>
                                <th scope="col">Total Count</th>
                                <th scope="col">Success Count</th>
                                <th scope="col">Success Recharge</th>
                                <th scope="col">Failure Recharge</th>
                                <th scope="col">Pending Recharge</th>
                                <th scope="col">Commision Given</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{int i = 0;}
                            @foreach (var item in Model.transanctionlist)
                            {
                                i++;

                                <tr align="left" valign="middle" style="color:#000066;background-color:White;">
                                    <td>@i</td>
                                    @*<td>@item.Transaction_Date_Time</td>*@
                                    <td>@item.Service_Name</td>
                                    <td>@item.Status</td>
                                    <td>@item.successcount</td>
                                    <td>@item.SuccessAmount</td>
                                    <td>@item.FailureAmount</td>
                                    <td>@item.PendingAmount</td>
                                    <td>@item.CommisionAmount</td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div id='OpenDilog'></div>
            </div>

        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {

    });
</script>



