PaymezonApp/PaymezonApp/Models/CompanyViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PaymezonDAL;

namespace PaymezonApp.Models
{
    public class CompanyViewModels
    {
        public int Pk_Company_Id { get; set; }
        public string Company_Name { get; set; }
        public string Company_Code { get; set; }
        public string Company_Detail1 { get; set; }
        public Nullable<bool> Is_deleted { get; set; }
        public List<Company_Detail> List_Company { get; set; }
        public Company_Detail dalcompany { get; set; }
        public List<Company_Detail> listcmpny { get; set; }
    }
}

PaymezonApp/PaymezonApp/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PaymezonBAL;
using PaymezonApp.Models;
using PaymezonDAL;


namespace PaymezonApp.Controllers
{
    public class CompanyController : Controller
    {
        //
        // GET: /Company/
        public ActionResult Index()
        {
            PaymezonDBEntities1 db = new PaymezonDBEntities1();
            CompanyViewModels cmnylist = new CompanyViewModels();
            cmnylist.List_Company = CompanyBAL.CompanyListorderbyname();
            return View(cmnylist);
        }

        public PartialViewResult CreateCompany()
        {
            return PartialView();
        }

        public PartialViewResult EditCompany (Int32 id)
        {

            CompanyViewModels obj = new CompanyViewModels();
            obj.dalcompany = CompanyBAL.GetCompanyByid(id);
            return PartialView(obj);
        }
        [HttpPost]
        public ActionResult AddCompany(Models.CompanyViewModels reg)
        {
            try
            {

                PaymezonDBEntities1 db = new PaymezonDBEntities1();
                Company_Detail usr = new Company_Detail();
                usr.Company_Name = reg.Company_Name;
                usr.Company_Code = reg.Company_Code;
                usr.Company_Detail1 = reg.Company_Detail1;          
                usr.Is_deleted = false;
                db.Company_Detail.Add(usr);
                db.SaveChanges();
                return RedirectToAction("../Company/Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        [HttpPost]
        public ActionResult DeleteCompany(long id)
        {

            CompanyBAL.DeleteCompany(id);
            return RedirectToAction("../Company/Index");

        }
        [HttpPost]
        public ActionResult UpdateCompany(Models.CompanyViewModels reg)
        {
            try
            {

                PaymezonDBEntities1 db = new PaymezonDBEntities1();
                Company_Detail usr = new Company_Detail();

                usr.Pk_Company_Id = reg.dalcompany.Pk_Company_Id;
                usr.Company_Name = reg.dalcompany.Company_Name;
                usr.Company_Code = reg.dalcompany.Company_Code;
                usr.Company_Detail1 = reg.dalcompany.Company_Detail1;

                CompanyBAL.UpdateCompany(usr);

                return RedirectToAction("../Company/Index");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult Blockoperatorbyuser() 
        {
            PaymezonDBEntities1 db = new PaymezonDBEntities1();
            CompanyViewModels cmnylist = new CompanyViewModels();
            cmnylist.List_Company = CompanyBAL.CompanyList();
            return View(cmnylist);
        }

	}
}

PaymezonApp/PaymezonApp/Views/Company/CreateCompany.cshtml
@model PaymezonApp.Models.CompanyViewModels

<link rel="stylesheet" type="text/css" id="theme" href="@Url.Content("~/admin/css/style.css")" />

<div class="modal fade" id="iconPreview" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            @using (Html.BeginForm("AddCompany", "Company", FormMethod.Post))
            {
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Create Company</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="Company_Name">Company Name</label>
                        <div class="form-line">
                            @Html.TextBoxFor(model => model.Company_Name, new { @class = "form-control", @placeholder = "Company Name" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Company_Code">Company Code</label>
                        <div class="form-line">
                            @Html.TextBoxFor(model => model.Company_Code, new { @class = "form-control", @placeholder = "Company Code" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Company_Detail1">Company Detail</label>
                        <div class="form-line">
                            @Html.TextAreaFor(model => model.Company_Detail1, new { @class = "form-control", @placeholder = "Company Details" })

                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-md-10">
                        <button class="btn btn-info mb-control" id="btnsave">Create</button>
                    </div>
                    <button type="button" class="btn btn-primary" data-dismiss="modal" data-target="#OpenDilog">Close</button>
                </div>   }
        </div>
    </div>
</div>

<script>
    
    $(function () {

        if ($(this).find("i").length > 0) {
            var iClass = $(this).find("i").attr("class");
        } else {
            var iClass = $(this).find("span").not("span[class=glyphicon-class]").attr("class");
        }

        var icon_preview = $("<i></i>").addClass(iClass);

        $("#iconPreview .icon-preview").html(icon_preview);

        $("#iconPreview .icon-preview-span").html('&lt;span class="' + iClass + '">&lt;/span>');
        $("#iconPreview .icon-preview-i").html('&lt;i class="' + iClass + '">&lt;/i>');
        $("#iconPreview .icon-preview-class").html(iClass);

        $("#iconPreview").modal("show");

    });
</script>


PaymezonApp/PaymezonApp/Views/Company/EditCompany.cshtml
@model PaymezonApp.Models.CompanyViewModels

<link rel="stylesheet" type="text/css" id="theme" href="@Url.Content("~/admin/css/style.css")" />

<div class="modal fade" id="iconPreview" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            @using (Html.BeginForm("UpdateCompany", "Company", FormMethod.Post))
            {
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Create Company</h4>
                </div>
                <div class="modal-body">
                   
                    @Html.HiddenFor(model => model.dalcompany.Pk_Company_Id)
                    <div class="form-group">
                        <label for="Company_Name">Company Name</label>
                        <div class="form-line">
                            @Html.TextBoxFor(model => model.dalcompany.Company_Name, new { @class = "form-control", @placeholder = "Company Name" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Company_Code">Company Code</label>
                        <div class="form-line">
                            @Html.TextBoxFor(model => model.dalcompany.Company_Code, new { @class = "form-control", @placeholder = "Company Code" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="Company_Detail1">Company Detail</label>
                        <div class="form-line">
                            @Html.TextAreaFor(model => model.dalcompany.Company_Detail1, new { @class = "form-control", @placeholder = "Company Details" })
                        </div>
                    </div>
                    </div>
                <div class="modal-footer">
                    <div class="col-md-10">
                        <button class="btn btn-info mb-control" id="btnsave">Update</button>
                    </div>
                    <button type="button" class="btn btn-primary" data-dismiss="modal" data-target="#OpenDilog">Close</button>
                </div>   }
        </div>
    </div>
</div>

<script>

    $(function () {

        if ($(this).find("i").length > 0) {
            var iClass = $(this).find("i").attr("class");
        } else {
            var iClass = $(this).find("span").not("span[class=glyphicon-class]").attr("class");
        }

        var icon_preview = $("<i></i>").addClass(iClass);

        $("#iconPreview .icon-preview").html(icon_preview);

        $("#iconPreview .icon-preview-span").html('&lt;span class="' + iClass + '">&lt;/span>');
        $("#iconPreview .icon-preview-i").html('&lt;i class="' + iClass + '">&lt;/i>');
        $("#iconPreview .icon-preview-class").html(iClass);

        $("#iconPreview").modal("show");

    });
</script>




PaymezonApp/PaymezonApp/Views/Company/Index.cshtml
@model PaymezonApp.Models.CompanyViewModels

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_adminlayout.cshtml";
}

<link rel="stylesheet" type="text/css" id="theme" href="@Url.Content("~/admin/css/style.css")" />

<style>
    #FUND th {
        vertical-align: top;
    }
</style>

<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="header">
                    <input type="button" id="show" name="name" class="btn btn-success pull-right" value="Add New Company" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Add Company" onclick="createCompany();" />

                    <h2>
                        Company Detail
                    </h2>
                </div>
                <div class="body">
                    <table class="table table-bordered table-striped table-hover dataTable js-exportable" id="Company">
                        <thead>
                            <tr>
                                <th>S.No.</th>
                                <th>Company Name</th>
                                <th>Company Code</th>
                                <th>Company Detail</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>S.No.</th>
                                <th>Company Name</th>
                                <th>Company Code</th>
                                <th>Company Detail</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @{int i = 0;}
                            @foreach (var item in Model.List_Company)
                            {
                                i++;
                                <tr>
                                    <td>@item.Pk_Company_Id</td>
                                    <td>@item.Company_Name</td>
                                    <td>@item.Company_Code</td>
                                    <td>@item.Company_Detail1</td>
                                    <td></td>
                                </tr>
                            }
                        </tbody>

                    </table>
                </div>
                <div id="OpenDilog">
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        GetCMNYJSON();
    });

    function createCompany() {
        var div = $("#OpenDilog");
        //$.mpb('show', { value: [0, 30], speed: 10, state: 'success' });
        div.load("/Company/CreateCompany", function () {

            //$.mpb("update", {
            //    value: 100, speed: 5, complete: function () {
            //        $(".mpb").fadeOut(200, function () {
            //            $(this).remove();
            //        });
            //    }
            //});
            div.modal('show', { backdrop: 'static' });
        });
    }

    function GetCMNYJSON() {
        $('#Company').dataTable({
            "bDestroy": true
        }).fnDestroy();

        window.table = $('#Company').DataTable({

            "columnDefs": [{
                "targets": -1,
                "data": null,
                "defaultContent": "<button id='edt' class='btn btn-default btn-rounded btn-sm' ><i class='material-icons'>edit</i></button>&nbsp;&nbsp;<button id='del' class='btn btn-default btn-rounded btn-sm edit'><i class='material-icons'>delete_sweep</i></button>"
            }],
            "bDestroy": true


        });
        $('#Company tbody').unbind().on('click', 'button', function ()
        {
            debugger;
            var data = window.table.row($(this).parents('tr')).data();
            if ($(this).attr('id') == 'edt') {

                EditAPI(data['0']);
            }
            if ($(this).attr('id') == 'del') {
                DeleteAPI(data['0']);
            }


        });
       
    }
    function EditAPI(Id) {

        var div = $("#OpenDilog");
       
        div.load("/Company/EditCompany?id=" + Id, function () {
       
            div.modal('show', { backdrop: 'static' });
        });
    }
    function DeleteAPI(Id) {
        if (confirm("Are You Sure to Delete ? ")) {

            var div = $("#OpenDilog");

            div.load("/Admin/deletedata?id=" + Id + "&pagename=DeleteCompany",
                function () {

                    div.modal('show', { backdrop: 'static' });
                });


            //$.ajax({

            //    url: "/Company/DeleteCompany?id=" + Id,
            //    type: "post",
            //    contentType: "application/json;charset=utf-8",
            //    success: function (data) {
            //        setTimeout(function () {
            //            GetAPIJSON()

            //        }, 500);

            //        ModalResponce(data, true);

            //    },
            //    error: function (xhr) {
            //        alert(xhr);
            //    }

            //});


        }
    }
</script>