PaymezonApp/PaymezonApp/Models/SupportViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using PaymezonDAL;


namespace PaymezonApp.Models
{
    public class SupportViewModels
    {
        public int Pk_Support_Id { get; set; }
        public string Token_no { get; set; }
        public string User_type { get; set; }
        public string Message { get; set; }
        public string Created_By { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<long> Answer_By { get; set; }
        public Nullable<System.DateTime> Answer_Date { get; set; }
        public string Content_Detail { get; set; }
        public string Is_Deleted { get; set; }

        public string Query_Type { get; set; }
        public string Mobile_Number { get; set; }
        public string Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int Company { get; set; }
        public List<Support_Detail> List_SupportDetail { get; set; }
        public List<Support_Detail> SupportDetail_byTokenID { get; set; }
        public string Company_name { get; set; }

        public string username { get; set; }
        public List<Company_Detail> List_Company { get; set; }
        [Required(ErrorMessage = "Please Select From Date")]
        public string fromdate { get; set; }
       
        public string todate { get; set; }
        public string message { get; set; }
    }
}

PaymezonApp/PaymezonApp/Controllers/SupportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PaymezonBAL;
using PaymezonApp.Models;
using PaymezonDAL;


namespace PaymezonApp.Controllers
{
    public class SupportController : Controller
    {

        public ActionResult Index()
        {
            if (Session["U_ID"] != null)
            {
                string fromdate = System.DateTime.Now.Date.ToString();
                string todate = "";
                long ID = Convert.ToInt64(Session["U_ID"]);
                PaymezonDBEntities1 db = new PaymezonDBEntities1();
                SupportViewModels msglist = new SupportViewModels();
                msglist.List_SupportDetail = SupportBAL.MSG_List_byId(ID, fromdate,todate);
                return View(msglist);
            }
            else
            {
                return RedirectToAction("../Register/Login");
            }
        }
        [HttpPost]
        public ActionResult Index(SupportViewModels reg)
        {
            if (Session["U_ID"] != null)
            {

                long ID = Convert.ToInt64(Session["U_ID"]);
                PaymezonDBEntities1 db = new PaymezonDBEntities1();
                SupportViewModels msglist = new SupportViewModels();
                if (ModelState.IsValid)
                {
                    msglist.List_SupportDetail = SupportBAL.MSG_List_byId(ID, reg.fromdate, reg.todate);
                    return View(msglist);
                }
                else
                {
                    msglist.message = "Please Select From Date or To Date.!";
                    msglist.List_SupportDetail = SupportBAL.MSG_List_byId(ID, reg.fromdate, reg.todate);
                    return View(msglist);
                }
            }
            else
            {
                return RedirectToAction("../Register/Login");
            }
        }
        public PartialViewResult AddNewSupport(string amt, string moblie, string OperatorCode)
        {
            PaymezonDBEntities1 db = new PaymezonDBEntities1();
            SupportViewModels obj = new SupportViewModels();
            //obj.Date = dt;
            obj.Company_name = OperatorCode;
            obj.Amount = amt;
            obj.Mobile_Number = moblie;
            //obj.Company = 1;
            obj.List_Company = CompanyBAL.CompanyList();
            return PartialView(obj);
        }

        public PartialViewResult ReplySupport(string TokenId)
        {
            SupportViewModels obj = new SupportViewModels();
            obj.Token_no = TokenId;
            obj.SupportDetail_byTokenID = SupportBAL.GetsinglesupportByid(TokenId);
            return PartialView(obj);

        }
        [HttpPost]

        public ActionResult ReplyToAdmin(Models.SupportViewModels reg)
        {
            try
            {
                PaymezonDBEntities1 db = new PaymezonDBEntities1();
                Support_Detail usr = new Support_Detail();

                long ID = Convert.ToInt64(Session["U_ID"]);

                usr.Token_no = reg.Token_no;
                usr.Content_Detail = reg.Content_Detail;
                usr.Created_By = Convert.ToInt32(ID);
                usr.Created_Date = System.DateTime.Now;
                usr.Is_Deleted = false;
                db.Support_Detail.Add(usr);
                db.SaveChanges();

                return RedirectToAction("../Support/index");
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }
        public ActionResult AddSupport(Models.SupportViewModels reg)
        {
            try
            {

                PaymezonDBEntities1 db = new PaymezonDBEntities1();
                Support_Detail usr = new Support_Detail();

                long ID = Convert.ToInt64(Session["U_ID"]);
                string labelID = Convert.ToString(this.Session["Label_ID"]);
                String usertype = Convert.ToString(this.Session["User_Type"]);
                usr.Token_no = "TK" + new Random().Next();
                usr.User_type = usertype;
                usr.Company = reg.Company;
                usr.Company_name = reg.Company_name;
                usr.Date = reg.Date;
                usr.Amount = reg.Amount;
                usr.Mobile_Number = reg.Mobile_Number;
                usr.Query_Type = reg.Query_Type;
                usr.Content_Detail = reg.Content_Detail;
                usr.Created_By = Convert.ToInt32(ID);
                usr.Created_Date = System.DateTime.Now;
                usr.Is_Deleted = false;
                db.Support_Detail.Add(usr);
                db.SaveChanges();
                return RedirectToAction("../Support/Index");

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

PaymezonApp/PaymezonApp/Views/Support/AddNewSupport.cshtml
@model PaymezonApp.Models.SupportViewModels

<link rel="stylesheet" type="text/css" id="theme" href="@Url.Content("~/css/theme-default.css")" />

<div class="modal fade" id="iconPreview" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            @using (Html.BeginForm("AddSupport", "Support", FormMethod.Post))
            {
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Add New Support</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">

                        <div class="row">
                            <div class="col-md-12">
                                <div class="panel-body">
                                    @* <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="col-md-4 col-xs-12 control-label">Company</label>
                                            <div class="col-md-8 col-xs-12">
                                                <div class="input-group">

                                                    @Html.DropDownListFor(model => model.Company, new SelectList(Model.List_Company, "Pk_Company_Id", "Company_Name"), new { @class = "form-control select" })
                                                </div>
                                                <span class="help-block">Please Enter Company Name</span>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-4 col-xs-12 control-label">Date</label>
                                            <div class="col-md-8 col-xs-12">
                                                <div class="input-group">

                                                    @Html.TextBoxFor(model => model.Date, new { @class = "form-control dt" })
                                                </div>
                                                <span class="help-block">Please Select Date</span>
                                            </div>
                                        </div>



                                                                        </div>*@
                                    <div class="col-md-12">
                                        <div class="block">
                                            <div class="form-group">
                                                <label class="col-md-4 col-xs-12 control-label">Operator Name</label>
                                                <div class="col-md-8 col-xs-12">
                                                    <div class="input-group">

                                                        @Html.TextBoxFor(model => model.Company_name, new { @class = "form-control " })
                                                        @*<input type="text" class="form-control" />*@
                                                    </div>
                                                    <span class="help-block">Please Enter Company Name</span>
                                                </div>
                                            </div>
                   

                                            <div class="form-group">
                                                <label class="col-md-4 col-xs-12 control-label">Amount</label>
                                                <div class="col-md-8 col-xs-12">
                                                    <div class="input-group">

                                                        @Html.TextBoxFor(model => model.Amount, new { @class = "form-control ", @type = "number", @maxlength = "10" })
                                                        @*<input type="text" class="form-control" />*@
                                                    </div>
                                                    <span class="help-block">Please Enter Amount</span>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-4 col-xs-12 control-label">Mobile Number</label>
                                                <div class="col-md-8 col-xs-12">
                                                    <div class="input-group">

                                                        @Html.TextBoxFor(model => model.Mobile_Number, new { @class = "form-control ", @type = "number"})
                                                        @*<input type="text" class="form-control" />*@
                                                    </div>
                                                    <span class="help-block">Please Enter Mobile Number</span>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-4 col-xs-12 control-label">Select Query Type</label>
                                                <div class="col-md-8 col-xs-12">
                                                    @{
                                                        var listmarital = new List<System.Web.UI.WebControls.ListItem>
                                                        {      
                                                            new System.Web.UI.WebControls.ListItem { Text = "Select Query Type", Value="0" },
                                                                new System.Web.UI.WebControls.ListItem { Text = "Failed", Value="Failed" },
                                                                new System.Web.UI.WebControls.ListItem { Text = "Benifit", Value="Benifit" },
                                                                new System.Web.UI.WebControls.ListItem { Text = "Login", Value="Login" },
                                                        };
                                                    }
                                                    <div class="input-group">
                                                        @Html.DropDownListFor(model => model.Query_Type, new SelectList(listmarital, "Value", "Text"), new { @class = "form-control select" })
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                    </div>

                                </div>
                                @*<div class="form-group">
                                    <div class="input-group">*@

                                @*<input type="text" class="form-control" />*@
                                @Html.TextAreaFor(model => model.Content_Detail, new { @class = "form-control", @placeholder = "Your Comment" })
                                @*</div>
                                        <span class="help-block">Please Enter Comment</span>
                                    </div>*@

                            </div>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-md-10">
                        <button class="btn btn-info mb-control" id="btnsave">Send Support</button>
                    </div>
                    <button type="button" class="btn btn-primary" data-dismiss="modal" data-target="#OpenDilog">Close</button>
                </div>
            }
        </div>
    </div>
</div>


<script>

    $(function () {

        $(".dt").datepicker();

        if ($(this).find("i").length > 0) {
            var iClass = $(this).find("i").attr("class");
        } else {
            var iClass = $(this).find("span").not("span[class=glyphicon-class]").attr("class");
        }

        var icon_preview = $("<i></i>").addClass(iClass);

        $("#iconPreview .icon-preview").html(icon_preview);

        $("#iconPreview .icon-preview-span").html('&lt;span class="' + iClass + '">&lt;/span>');
        $("#iconPreview .icon-preview-i").html('&lt;i class="' + iClass + '">&lt;/i>');
        $("#iconPreview .icon-preview-class").html(iClass);

        $("#iconPreview").modal("show");

    });
</script>

<style type="text/css">
    div.datepicker {
        z-index: 10000 !important;
    }
</style>

PaymezonApp/PaymezonApp/Views/Support/Index.cshtml
@model PaymezonApp.Models.SupportViewModels

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            @*<div class="card">
                <br />
                <div class="header">
                    <h2>
                        Support System
                    </h2>
                </div>

                   

                   <input type="button" id="show" name="name" class="btn btn-success pull-left" value="Add New Support" onclick="AddSupport();" />

                 
               
            </div>*@
            <br />
            <br />
@using (Html.BeginForm("Index", "Support", FormMethod.Post))
      {
            <div class="panel panel-success panel-hidden-controls">
                <div class="panel-heading">
                    <h3 class="panel-title"> Support System</h3>
                </div>
                <div class="panel-body">

                    <div class="col-md-4">
                        <label class="col-md-4 control-label">From Date :</label>
                        <div class="input-group">
                            <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
                            @Html.TextBoxFor(model => model.fromdate, new { @class = "form-control dt", @placeholder = "Please choose a date..." })
                        </div>
                        <br/>
                        <p style="color: red;">@Html.DisplayFor(model => model.message)</p>
                    </div>
                    <div class="col-md-4">
                        <label class="col-md-4 control-label">To Date :</label>
                        <div class="input-group">
                            <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
                            @Html.TextBoxFor(model => model.todate, new { @class = "form-control dt", @placeholder = "Please choose a date..." })
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <input type="button" id="show" name="name" class="btn btn-success pull-left" value="Add New Support" onclick="AddSupport();" />
                    <button class="btn btn-success pull-right">Search</button>
                </div>
            </div>
      }

            <div class="panel panel-default">
                <div class="panel-body">

                    <table class="table datatable" id="Support" cellspacing="0" cellpadding="3" rules="all" border="1" style="background-color: White; border-color: #CCCCCC; border-width: 1px; border-style: None; font-weight: normal; font-style: normal; text-decoration: none; width: 100%; border-collapse: collapse; ">
                     
                        <thead>
                            <tr align="left" style="color:Black;background-color:#DBE4E8;font-weight:bold;">
                                <th scope="col">Sr No.</th>
                                <th scope="col">Support ID</th>
                                <th scope="col">Token NO</th>
                                <th scope="col">Query Type</th>
                                <th scope="col">Date</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{int i = 0;}
                            @foreach (var item in Model.List_SupportDetail)
                            {
                                i++;

                                <tr align="left" valign="middle" style="color:#000066;background-color:White;">
                                    <td>@i</td>
                                    <td>@item.Pk_Support_Id</td>
                                    <td>@item.Token_no</td>
                                    <td>@item.Query_Type</td>
                                    <td>@item.Created_Date</td>
                                    <td></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div id='OpenDilog'></div>
            </div>
            @*<div class="content-frame-body content-frame-body-left">

                                <div class="messages messages-img">
                                    @foreach (var item in Model.List_SupportDetail)
                                            {
                                <div class="item in">
                                    <div class="image">

                                    </div>
                                    <div class="text">
                                        <div class="heading">
                                            <a href="#">@item.Message</a>
                                            <span class="date">@item.Created_Date</span>
                                        </div>
                                        @item.Content_Detail
                                    </div>
                                </div>
                }
                                </div>

                            </div>*@

        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {

        GetSupportJSON();
    });
    function AddSupport() {
        var div = $("#OpenDilog");
        $.mpb('show', { value: [0, 30], speed: 10, state: 'success' });
        div.load("/Support/AddNewSupport", function () {
            $.mpb("update", {
                value: 100, speed: 5, complete: function () {
                    $(".mpb").fadeOut(200, function () {
                        $(this).remove();
                    });
                }
            });
            div.modal('show', { backdrop: 'static' });
        });
    }
    function GetSupportJSON() {
        debugger;
        $('#Support').dataTable({
            "bDestroy": true
        }).fnDestroy();

        window.table = $('#Support').DataTable({

            "columnDefs": [{
                "targets": -1,
                "data": null,
                "defaultContent": "<button id='edt' class='btn btn-default btn-rounded btn-sm' ><i class='material-icons'>edit</i></button>"
            }],
            "bDestroy": true


        });
        $('#Support tbody').unbind().on('click', 'button', function () {
            debugger;
            var data = window.table.row($(this).parents('tr')).data();
            if ($(this).attr('id') == 'edt') {

                ReplySupport(data['1']);
            }
            //if ($(this).attr('id') == 'del') {
            //    DeleteSupport(data['0']);
            //}
        });
    }
    function ReplySupport(TokenId)
    {

        debugger;
        var div = $("#OpenDilog");

        div.load("/Support/ReplySupport?TokenId=" + TokenId, function () {

            div.modal('show', { backdrop: 'static' });
        });
    }
    //function DeleteSupport(Id) {
    //    if (confirm("Are You Sure to Delete ? ")) {
    //        $.ajax({

    //            url: "/Admin/DeleteAPI?Apiid=" + Id,
    //            type: "post",
    //            contentType: "application/json;charset=utf-8",
    //            success: function (data) {
    //                setTimeout(function () {
    //                    GetSupportJSON()

    //                }, 500);

    //                ModalResponce(data, true);

    //            },
    //            error: function (xhr) {
    //                alert(xhr);
    //            }

    //        });


    //    }
    //}

</script>



PaymezonApp/PaymezonApp/Views/Support/ReplySupport.cshtml
@model PaymezonApp.Models.SupportViewModels

<link rel="stylesheet" type="text/css" id="theme" href="@Url.Content("~/css/theme-default.css")" />

<div class="modal fade" id="iconPreview" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            @using (Html.BeginForm("ReplyToAdmin", "Support", FormMethod.Post))
            {
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Add New Support</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">

                        <div class="row">
                            <div class="col-md-12">
                                @*<div class="content-frame">
                                    <div class="content-frame-body content-frame-body-left">*@
                                        <div class="messages messages-img">

                                            @foreach (var item in Model.SupportDetail_byTokenID)
                                            {
                                                @Html.HiddenFor(model => item.Pk_Support_Id)
                                                @Html.HiddenFor(model => item.Token_no)
                                                @Html.HiddenFor(model => item.User_type)
                                                @Html.HiddenFor(model => item.Message)

                                                if (item.Answer_By == null)
                                                {

                                                    <div class="item in item-visible">
                                                        <div class="image">
                                                        </div>
                                                        <div class="text">
                                                            <div class="heading">
                                                                <a href="#">Me :@item.Query_Type</a>
                                                                <span class="date">@item.Created_Date</span>
                                                            </div>
                                                            @item.Content_Detail
                                                        </div>
                                                    </div>


                                                }
                                                else
                                                {

                                                    <div class="item in item-visible">
                                                        <div class="image">
                                                        </div>
                                                        <div class="text">
                                                            <div class="heading">
                                                                <a href="#">From Admin :@item.Query_Type</a>
                                                                <span class="date">@item.Answer_Date</span>
                                                            </div>
                                                            @item.Content_Detail
                                                        </div>
                                                    </div>

                                                }

                                            }

                                            <div class="form-group">
                                                @Html.HiddenFor(model => model.Token_no)
                                                @Html.TextAreaFor(model => model.Content_Detail, new { @class = "form-control", @placeholder = "Reply To Admin" })
                                                <span class="help-block">Please Send Your Review</span>
                                            </div>

                                        </div>
                                    @*</div>
                                </div>*@
                                </div>
                        </div>

                    </div>
                </div>
                <div class="modal-footer">
                    <div class="col-md-10">
                        <button class="btn btn-info mb-control" id="btnsave">Send Support</button>
                    </div>
                    <button type="button" class="btn btn-primary" data-dismiss="modal" data-target="#OpenDilog">Close</button>
                </div>
            }
        </div>
    </div>
</div>






<script>


    $(function () {



        if ($(this).find("i").length > 0) {
            var iClass = $(this).find("i").attr("class");
        } else {
            var iClass = $(this).find("span").not("span[class=glyphicon-class]").attr("class");
        }

        var icon_preview = $("<i></i>").addClass(iClass);

        $("#iconPreview .icon-preview").html(icon_preview);

        $("#iconPreview .icon-preview-span").html('&lt;span class="' + iClass + '">&lt;/span>');
        $("#iconPreview .icon-preview-i").html('&lt;i class="' + iClass + '">&lt;/i>');
        $("#iconPreview .icon-preview-class").html(iClass);

        $("#iconPreview").modal("show");

    });
</script>
